# -*- coding: utf-8 -*-
"""Netflix data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6RkQrfTUiaE1f42EuWwz4mm-bWEiBct
"""

pip install pandas numpy matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("netflix_titles.csv.zip")

df.head()

df.tail()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df.fillna("Unknown", inplace=True)

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

df['year_added'] = df['date_added'].dt.year

df['type'].value_counts()

df['type'].value_counts().plot(kind='bar')

plt.title("Movies vs TV Shows")

plt.show()

df['country'].value_counts().head(10)

df['country'].value_counts().head(10).plot(kind='bar')

plt.title("Top Countries")

plt.show()

df['rating'].value_counts()

df['rating'].value_counts().plot(kind='bar')

plt.title("Ratings")

plt.show()

df['director'].value_counts().head(10)

movies = df[df['type']=="Movie"]

movies['release_year'].value_counts().sort_index().plot()

plt.title("Movies Released Per Year")

plt.show()

df['year_added'].value_counts().sort_index().plot()

plt.title("Netflix Content Added Every Year")

plt.show()

df['listed_in'].value_counts().head(10)

movies.sort_values('duration',ascending=False).head()

movies.sort_values('release_year').head()

movies.sort_values('release_year',ascending=False).head()

df.to_csv("cleaned_netflix.csv", index=False)

from google.colab import files

files.download("cleaned_netflix.csv")